name: retail_buah_app
description: "Aplikasi Retail Buah Segar menggunakan Flutter dan Express.js"

# Versi aplikasi
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Library untuk koneksi ke API Express.js
  dio: ^5.4.0

  # Untuk memformat mata uang (Rp) dan tanggal
  intl: ^0.19.0

  # Untuk mengetahui platform (Android/iOS) secara otomatis
  path_provider: ^2.1.2

  # Google Fonts agar tampilan lebih modern (Opsional)
  google_fonts: ^6.1.0

  # Icons tambahan (Opsional)
  cupertino_icons: ^1.0.6
  
  image_picker: ^1.0.7
  crypto: ^3.0.7
  barcode: ^2.2.9
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Jika nanti kamu punya folder gambar/aset, aktifkan di sini:
  # assets:
  #   - assets/images/